# Generated by Django 5.0.2 on 2024-02-10 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_alter_pet_slug'),
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PetPhotos',
            new_name='PetPhoto',
        ),
    ]
