# Generated by Django 5.0.2 on 2024-02-10 21:24

import petstagram.photos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_petphoto_created_at_petphoto_modified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petphoto',
            name='photo',
            field=models.ImageField(upload_to='pet_photos/', validators=[petstagram.photos.models.MaxFileSizeValidator(limit_value=5242880)]),
        ),
    ]
